#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
<<comment
Requirements:

    The redirection must be a “301 Moved Permanently”
    You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
    Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task
comment

sudo apt-get update
sudo apt-get -y install nginx
sudo afw allow 'Nginx HTTP'
sudo chmod ugo+rwx /var/www/html/
sudo echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
