#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
<<Comment
Requirements:

    The page must return an HTTP 404 error code
    The page must contain the string Ceci n'est pas une page
    Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

Comment
sudo apt-get update
sudo apt-get -y install nginx
sudo afw allow 'Nginx HTTP'
sudo chmod ugo+rwx /var/www/html/
sudo echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
