#!/usr/bin/env bash

# Write a Bash script that displays the PID, along with the process name, of
# processes whose name contain the word bash.

# Requirements:
# You cannot use ps

for i in $(pidof bash); do
echo "$i bash"

done
