#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinitely.
trap "echo \"I am invincible!!!\"" SIGTERM
trap "echo \"Killed\";exit" SIGQUIT
while true; do
   echo "To infinity and beyond"
   sleep 2
done