#!/usr/bin/env bash
# FizzBuzz Challenge

for i in {1..100}; do

  if [ $i % 3 -eq 0 ] && [ $i % 5 -eq 0 ]
  then
    echo "FizzBuzz"
    ((i++))
  elif [ ($i % 3) -eq 0 ]
  then
    echo "Fizz"
    ((i++))

  elif [ ($i % 5) -eq 0 ]; then
    #statements
    echo "Buzz"
    ((i++))
  else
    echo $i
    ((i++))
  fi
done
