#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

l=1

while [ $l -le 10 ]; do
  if [ $l -eq 9 ]
  then
    echo "Holberton School"
    echo "Hi"
    ((l++))
  else
    echo "Holberton School"
    ((l++))
  fi
done
