#!/usr/bin/env bash
# This script displays "Holberton School" 10 times but,
# In fourth print "bad luck"
# In eighth "good luck"

l=1

while [ $l -le 10 ]; do

  if [ $l -eq 4 ]
  then
    echo "bad luck"
    ((l++))
  elif [ $l -eq 8 ]
  then
    echo "good luck"
    ((l++))
  else
    echo "Holberton School"
    ((l++))
  fi
done
