#!/usr/bin/env bash
# This script displays "Holberton School" 20 times but,
# In 4th print "bad luck from China"
# In 9th "good luck from Japan"
# and 17th "bad luck from Italy"

l=1

while [ $l -le 20 ]; do

  case $l in
    4 ) echo $l | echo "bad luck from China" && ((l++));;
    9 ) echo $l | echo "bad luck from Japan" && ((l++));;
    17) echo $l | echo "bad luck from Italy" && ((l++));;
    * ) echo $l && ((l++))
  esac

done
