#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8
cp /etc/hosts /etc/hosts.new
if [ -f /etc/hosts.new ];then
    sed -i 's/127.0.0.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' /etc/hosts.new
    mv -f /etc/hosts.new /etc/hosts
    if [ $? == 0 ];then
        exit 0
    else
        exit 1
    fi
else
    exit 1
fi